#########################
#                       #
#   RazDonators 1.0.2   #
#                       #
#########################
DONATOR-PERMISSION: "online.donator"
NO-DONATORS-ONLINE: "&fNo Donators"
ANNOUNCE-MESSAGE:
  - ''
  - '&6Online Donators: &f%donators%'
  - '&7If you want to be featured on this list purchase rank.'
  - ''
